version: 2.1

jobs:
  job_a:
    docker:
      - image: cimg/node:16.20.2
    working_directory: ~/repo
    steps:
      - run: "true"

  job_b:
    docker:
      - image: cimg/node:16.20.2
    steps:
      - run: "true"

workflows:
  version: 2.1

  main:
    jobs:
      - job_a
      - job_b
